storage: add the option to remove a ZFS storage pool
When a ZPool data structure exists, attempting to do a GuidedTargetReformat was
leading to the following exception:

  File "subiquity/server/controllers/filesystem.py", line 816, in start_guided_reformat
    self.reformat(disk, ptable=target.ptable, wipe="superblock-recursive")
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "subiquity/common/filesystem/manipulator.py", line 287, in reformat
    self.delete_partition(
    ~~~~~~~~~~~~~~~~~~~~~^
        p, override_preserve=True, allow_renumbering=False, allow_moving=False
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "subiquity/common/filesystem/manipulator.py", line 138, in delete_partition
    self.clear(part)
    ~~~~~~~~~~^^^^^^
  File "subiquity/common/filesystem/manipulator.py", line 279, in clear
    self.delete(subobj)
    ~~~~~~~~~~~^^^^^^^^
  File "subiquity/common/filesystem/manipulator.py", line 270, in delete
    getattr(self, "delete_" + obj.type)(obj)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FilesystemController' object has no attribute 'delete_zpool'. Did you mean: 'create_zpool'?

If probert were to report data in the "zfs" section, it would probably prevent
the installation from happening because of the bug above. That said, probert
does not automatically import zpools so that would need to be an action from
the user. Furthermore, even when a zpool is imported, probert seems to ignore
it for unknown reasons.

As a consequence, the bug does not currently prevent existing ZFS installs from
being overwritten. That said, it is possible to hit it using the
/storage/v2/guided API directly.

LP: #2057673

Signed-off-by: Olivier Gayot <olivier.gayot@canonical.com>