async_helpers: only pass a single positional argument to create_task
asyncio.create_task only accepts one positional argument and passing
more than one results in the following exception:

TypeError: create_task() takes 1 positional argument but 2 were given

Therefore, it does not make sense for run_bg_task to forward *args to
it. We now use explicit keyword argument names.

Signed-off-by: Olivier Gayot <olivier.gayot@canonical.com>