storage: fix crash with a pre-existing RAID without path in autoinstall
When the storage config of an autoinstall specifies a pre-existing RAID
without an explicit path, we have no information about the underlying
block device. Computing the size of the RAID then fails with:

  AttributeError: 'NoneType' object has no attribute 'size'

Before we switched to ._info to get the size of pre-existing RAIDs, the
block device was looked up from the name of the RAID, so specifying the
path was not needed. Restore that behavior, and fall back to estimating
the size of the RAID if the block device cannot be found.

LP: #2119507
LP: #2165894