storage: when handling a partition, ignore any FS at the disk level
The parts_and_gaps function returned no partition nor gap when the disk
itself has (or had) a file-system signature. This is to make sure we
don't partition a disk that is already used unpartioned.

However, when we are operating on an existing partition of a disk, we
should not pretend that the underlying disk has no partition ; even if
the disk itself has a FS signature. This leads to a common issue when
doing GuidedTargetReformat:

  Traceback (most recent call last):
    File "subiquity/common/api/server.py", line 164, in handler
      result = await implementation(**args)
    File "subiquity/server/controllers/filesystem.py", line 1184, in v2_guided_POST
      await self.guided(data)
    File "subiquity/server/controllers/filesystem.py", line 726, in guided
      gap = self.start_guided(choice.target, disk)
    File "/usr/lib/python3.10/functools.py", line 926, in _method
      return method.__get__(obj, cls)(*args, **kwargs)
    File "subiquity/server/controllers/filesystem.py", line 645, in start_guided_reformat
      self.reformat(disk, wipe="superblock-recursive")
    File "subiquity/common/filesystem/manipulator.py", line 257, in reformat
      self.delete_partition(p, True)
    File "subiquity/common/filesystem/manipulator.py", line 120, in delete_partition
      self.model.remove_partition(part)
    File "subiquity/models/filesystem.py", line 2110, in remove_partition
      for p2 in movable_trailing_partitions_and_gap_size(part)[0]:
    File "/usr/lib/python3.10/functools.py", line 889, in wrapper
      return dispatch(args[0].__class__)(*args, **kw)
    File "subiquity/common/filesystem/gaps.py", line 281, in
         _movable_trailing_partitions_and_gap_size_partition
      part_idx = pgs.index(partition)
  ValueError: Partition(device=disk-sda, ...) is not in list

LP: #2081738

Signed-off-by: Olivier Gayot <olivier.gayot@canonical.com>
(cherry picked from commit 8c5f293c28edefaccb4822b1ff3b996429b8b6bd)