storage: handle scenario where an availability-check-error has no action
For certain types of errors such as "system-not-efi", snapd does not return any
action. And when there is no action, snapd does not return an empty list, it
returns an error with no "actions" property.

Make sure we don't crash with a:

 TypeError: AvailabilityCheckError.__init__() missing 1 required keyword-only
            argument: 'actions'

Signed-off-by: Olivier Gayot <olivier.gayot@canonical.com>