test: make make_filesystem append to model._actions
make_filesystem constructed Filesystem(...) directly without appending it
to model._actions, unlike the production add_filesystem.  Any code path
that later calls delete_filesystem raised an exception because the filesytem
was never registered:

    ValueError: list.remove(x): x not in list

Append the filesystem to _actions in make_filesystem so we can confidently call
delete_filesystem.

Signed-off-by: Olivier Gayot <olivier.gayot@canonical.com>
(cherry picked from commit 6c27f7bef1c4f2ebf71f7e6cbec085a48f8a5979)