server: do not crash when the cloud-init status is unknown
cloud_init_status_wait() returns None as the status when the output of
`cloud-init status` cannot be parsed. wait_for_cloudinit() would then
crash with:

  TypeError: argument of type 'NoneType' is not iterable

Only skip loading the cloud-config when we know for sure that cloud-init
is disabled. Otherwise, load it as we did before the "disabled" check
was introduced.

LP: #2162007